# texts.py
TEXTS = {
    "en": {
        "main_title": "RIPPERBOT",
        "api_connected": "✅",
        "api_disconnected": "❌",
        "live_log": "📡 LIVE LOG",
        "no_claims": "⏳ No claims yet...",
        "crane_active_indicator": "✅",
        "crane_inactive_indicator": "⚠️",
        "add_account": "➕ Add Account",
        "back": "◀️ Back",
        "control_panel": "Control Panel",
        "claims": "claims",
        "balance": "💰 Balance",
        "subscription": "💳 Subscription",
        "invite_friend": "🎁 Invite Friend",
        "settings": "⚙️ Settings",
        "refresh": "🔄",
        "active_accounts": "ACTIVE ACCOUNTS",
        "no_accounts": "No active accounts — + to add",
        "settings_title": "⚙️ Settings",
        "api_key_label": "🔑 API Key",
        "api_host_label": "🌐 API Host",
        "api_key_not_set": "❌ Not set",
        "api_key_set": "✅",
        "settings_note": "Each user has their own API key.",
        "language": "🌐 Language",
        "select_language": "🌐 Select your language:",
        "language_changed": "✅ Language changed!",
        "subscription_title": "💳 Subscription",
        "no_active_sub": "❌ No active subscription",
        "accounts_count": "📊 Accounts: 0",
        "claims_count": "📊 Claims: 0",
        "available_plans": "✅ Available plans:",
        "monthly": "📆 Monthly – $15/month",
        "monthly_desc": "├ 50 accounts (any site)\n└ Unlimited claims",
        "claim_pack": "🎫 Claim Pack – $1/1200 claims",
        "claim_pack_desc": "├ Unlimited accounts\n└ 1200 claims per pack",
        "pay_with_crypto": "💎 Pay with Crypto",
        "select_crypto": "💎 Select Cryptocurrency\n\nChoose your preferred coin:",
        "bnb": "🟡 BNB (BEP-20)",
        "sol": "🟠 SOL",
        "ltc": "⚪ LTC",
        "ton": "💎 TON",
        "trx": "🔴 TRX (TRC-20)",
        "doge": "🐕 DOGE",
        "wallet_address": "📍 Wallet Address:",
        "amounts": "💰 Deposit any amount ($0.1 – $100 USD):",
        "send_exact": "⚠️ Send exactly the amount you entered",
        "submit_txid": "📝 After payment, tap Submit Screenshot",
        "submit_txid_button": "📸 Submit Screenshot",
        "enter_amount": "💰 Enter the amount in USD (min $0.1, max $100):",
        "enter_txid": "📸 Now send the payment screenshot:",
        "deposit_request": "💸 Deposit request from user {user_id}\nAmount: ${amount}\nProof: {txid}",
        "approve": "✅ Approve",
        "reject": "❌ Reject",
        "deposit_approved": "✅ Your deposit of ${amount} has been approved! Balance updated.",
        "deposit_rejected": "❌ Your deposit request has been rejected. Please try again.",
        "txid_received": "📸 Screenshot received! Admin will review and add balance.",
        "cancel": "❌ Cancel",
        "skip_cookies": "⏭️ Skip Cookies",
        "skip_ua": "⏭️ Skip UA",
        "add_account_title": "Add Account — {crane}",
        "label": "🏷️ Label: {label}",
        "send_email": "📧 Send the account email:",
        "cancel_abort": "/cancel to abort.",
        "email_received": "📧 Email: <code>{email}</code>",
        "send_password": "🔑 Now send the password:",
        "password_ok": "🔑 Password: ✅",
        "cookies_optional": "🍪 Cookies (optional — send cookies or tap Skip):",
        "cookies_instruction": "F12 > Console > <code>document.cookie</code>",
        "cookies_skipped": "🍪 Cookies: ⏭️ Skipped",
        "ua_optional": "🌐 User-Agent (optional — send UA or tap Skip):",
        "ua_instruction": "F12 > Console > <code>navigator.userAgent</code>",
        "cookies_received": "🍪 Cookies: ✅ ({len} chars)",
        "account_added": "✅ <b>Account added!</b>",
        "account_num": "{crane} #{num}",
        "cookies_status": "🍪 {status}",
        "ua_status": "🌐 UA: {status}",
        "main_menu": "🏠 Main Menu",
        "cancelled": "❌ Cancelled.",
        "updated": "♻️ Updated!",
        "not_found": "Not found!",
        "api_key_prompt": "🔑 <b>XEvil API Key</b>\n\nSend your API key:\n\n/cancel to abort.",
        "api_host_prompt": "🌐 <b>API Host</b>\n\nSend the API host (e.g. <code>sctg.xyz</code>):\n\n/cancel to abort.",
        "referral_title": "🎁🎁 <b>Referral System</b>",
        "your_link": "🔗 <b>Your referral link:</b>",
        "share_text": "📢 <b>Share this link with your friends!</b>\n├ You get: <b>+16 claims</b>\n└ Your friend gets: <b>+8 claims</b>",
        "friends_joined": "👥 <b>Friends joined:</b> {count}",
        "bonus_earned": "📊 <b>Bonus claims earned:</b> {bonus}",
        "share_button": "📨 Share with Friend",
        "balance_title": "💰 <b>My Balance</b>",
        "current_balance": "💵 Current balance: <b>${balance}</b>",
        "total_deposited": "📥 Total deposited: <b>${deposited}</b>",
        "total_spent": "📤 Total spent on captcha: <b>${spent}</b>",
        "spent_note": "\n<i>Each claim costs $0.01 (1 cent)</i>",
        "add_balance_usage": "Admin: /add_balance <user_id> <amount>",
        "add_spent_usage": "Admin: /add_spent <user_id> <amount>",
        "balance_updated": "✅ Balance updated for user {user_id}: +${amount}, new balance: ${balance}",
        "spent_updated": "✅ Spent updated for user {user_id}: +${amount}, new spent: ${spent}",
        "invalid_amount": "❌ Invalid amount. Please enter a number between 0.1 and 100.",
        "user_not_found": "❌ User not found.",
        "admin_only": "❌ Admin command only.",
        "referral_bonus": "🎉 You got +16 claims! Referred by user {ref_id}",
        "referee_bonus": "🎉 Your friend got +8 claims for joining via your link!",
    },
    "uz": {
        "main_title": "RIPPERBOT",
        "api_connected": "✅",
        "api_disconnected": "❌",
        "live_log": "📡 JONLI LOG",
        "no_claims": "⏳ Hali hech qanday claim yo‘q...",
        "crane_active_indicator": "✅",
        "crane_inactive_indicator": "⚠️",
        "add_account": "➕ Hisob qo‘shish",
        "back": "◀️ Orqaga",
        "control_panel": "Boshqaruv paneli",
        "claims": "claim",
        "balance": "💰 Balans",
        "subscription": "💳 Obuna",
        "invite_friend": "🎁 Do‘st taklif qilish",
        "settings": "⚙️ Sozlamalar",
        "refresh": "🔄",
        "active_accounts": "FAOL HISOBLAR",
        "no_accounts": "Faol hisoblar yo‘q — + qo‘shish",
        "settings_title": "⚙️ Sozlamalar",
        "api_key_label": "🔑 API kalit",
        "api_host_label": "🌐 API host",
        "api_key_not_set": "❌ O‘rnatilmagan",
        "api_key_set": "✅",
        "settings_note": "Har bir foydalanuvchi o‘z API kalitiga ega.",
        "language": "🌐 Til",
        "select_language": "🌐 Tilni tanlang:",
        "language_changed": "✅ Til o‘zgartirildi!",
        "subscription_title": "💳 Obuna",
        "no_active_sub": "❌ Faol obuna yo‘q",
        "accounts_count": "📊 Hisoblar: 0",
        "claims_count": "📊 Claimlar: 0",
        "available_plans": "✅ Mavjud rejalar:",
        "monthly": "📆 Oylik – $15/oy",
        "monthly_desc": "├ 50 ta hisob (istalgan sayt)\n└ Cheksiz claim",
        "claim_pack": "🎫 Claim paketi – $1/1200 claim",
        "claim_pack_desc": "├ Cheksiz hisob\n└ 1200 claim",
        "pay_with_crypto": "💎 Kripto bilan to‘lash",
        "select_crypto": "💎 Kriptovalyutani tanlang\n\nO‘zingizga qulay tangani belgilang:",
        "bnb": "🟡 BNB (BEP-20)",
        "sol": "🟠 SOL",
        "ltc": "⚪ LTC",
        "ton": "💎 TON",
        "trx": "🔴 TRX (TRC-20)",
        "doge": "🐕 DOGE",
        "wallet_address": "📍 Hamyon manzili:",
        "amounts": "💰 Istalgan miqdorni kiriting ($0.1 – $100 USD):",
        "send_exact": "⚠️ Aynan kiritgan miqdorni yuboring",
        "submit_txid": "📝 To‘lovdan so‘ng Screenshot yuboring",
        "submit_txid_button": "📸 Screenshot yuborish",
        "enter_amount": "💰 USD miqdorini kiriting (min $0.1, max $100):",
        "enter_txid": "📸 Endi to‘lov skrinshotini yuboring:",
        "deposit_request": "💸 {user_id} foydalanuvchidan to‘lov so‘rovi\nMiqdor: ${amount}\nTasdiq: {txid}",
        "approve": "✅ Tasdiqlash",
        "reject": "❌ Rad etish",
        "deposit_approved": "✅ ${amount} miqdoridagi to‘lovingiz tasdiqlandi! Balans yangilandi.",
        "deposit_rejected": "❌ To‘lov so‘rovingiz rad etildi. Qaytadan urinib ko‘ring.",
        "txid_received": "📸 Skrinshot qabul qilindi! Admin tekshirib balansni oshiradi.",
        "cancel": "❌ Bekor qilish",
        "skip_cookies": "⏭️ Cookies o‘tkazib yuborish",
        "skip_ua": "⏭️ UA o‘tkazib yuborish",
        "add_account_title": "Hisob qo‘shish — {crane}",
        "label": "🏷️ Label: {label}",
        "send_email": "📧 Hisob emailini yuboring:",
        "cancel_abort": "/cancel bekor qilish.",
        "email_received": "📧 Email: <code>{email}</code>",
        "send_password": "🔑 Endi parolni yuboring:",
        "password_ok": "🔑 Parol: ✅",
        "cookies_optional": "🍪 Cookies (ixtiyoriy — cookies yuboring yoki Skip bosing):",
        "cookies_instruction": "F12 > Konsol > <code>document.cookie</code>",
        "cookies_skipped": "🍪 Cookies: ⏭️ O‘tkazib yuborildi",
        "ua_optional": "🌐 User-Agent (ixtiyoriy — UA yuboring yoki Skip bosing):",
        "ua_instruction": "F12 > Konsol > <code>navigator.userAgent</code>",
        "cookies_received": "🍪 Cookies: ✅ ({len} belgi)",
        "account_added": "✅ <b>Hisob qo‘shildi!</b>",
        "account_num": "{crane} #{num}",
        "cookies_status": "🍪 {status}",
        "ua_status": "🌐 UA: {status}",
        "main_menu": "🏠 Bosh menyu",
        "cancelled": "❌ Bekor qilindi.",
        "updated": "♻️ Yangilandi!",
        "not_found": "Topilmadi!",
        "api_key_prompt": "🔑 <b>XEvil API kaliti</b>\n\nAPI kalitingizni yuboring:\n\n/cancel bekor qilish.",
        "api_host_prompt": "🌐 <b>API host</b>\n\nAPI hostni yuboring (masalan <code>sctg.xyz</code>):\n\n/cancel bekor qilish.",
        "referral_title": "🎁🎁 <b>Referal tizimi</b>",
        "your_link": "🔗 <b>Sizning referal linkingiz:</b>",
        "share_text": "📢 <b>Do‘stlaringizga ulashing!</b>\n├ Siz: <b>+16 claim</b>\n├ Do‘stingiz: <b>+8 claim</b>",
        "friends_joined": "👥 <b>Qo‘shilgan do‘stlar:</b> {count}",
        "bonus_earned": "📊 <b>Bonus claimlar:</b> {bonus}",
        "share_button": "📨 Do‘stga ulashish",
        "balance_title": "💰 <b>Mening balansim</b>",
        "current_balance": "💵 Joriy balans: <b>${balance}</b>",
        "total_deposited": "📥 Jami to‘ldirilgan: <b>${deposited}</b>",
        "total_spent": "📤 Captchaga sarflangan: <b>${spent}</b>",
        "spent_note": "\n<i>Har bir claim $0.01 (1 sent) turadi</i>",
        "add_balance_usage": "Admin: /add_balance <user_id> <amount>",
        "add_spent_usage": "Admin: /add_spent <user_id> <amount>",
        "balance_updated": "✅ {user_id} foydalanuvchi balansi +${amount}, yangi balans: ${balance}",
        "spent_updated": "✅ {user_id} foydalanuvchi sarfi +${amount}, yangi sarf: ${spent}",
        "invalid_amount": "❌ Noto‘g‘ri miqdor. Iltimos 0.1 va 100 orasida son kiriting.",
        "user_not_found": "❌ Foydalanuvchi topilmadi.",
        "admin_only": "❌ Faqat admin buyrug‘i.",
        "referral_bonus": "🎉 Siz +16 claim oldingiz! Sizni {ref_id} taklif qildi.",
        "referee_bonus": "🎉 Do‘stingiz sizning link orqali kelib +8 claim oldi!",
    },
    "ru": {
        "main_title": "RIPPERBOT",
        "api_connected": "✅",
        "api_disconnected": "❌",
        "live_log": "📡 ЖИВОЙ ЛОГ",
        "no_claims": "⏳ Пока нет клеймов...",
        "crane_active_indicator": "✅",
        "crane_inactive_indicator": "⚠️",
        "add_account": "➕ Добавить аккаунт",
        "back": "◀️ Назад",
        "control_panel": "Панель управления",
        "claims": "клеймы",
        "balance": "💰 Баланс",
        "subscription": "💳 Подписка",
        "invite_friend": "🎁 Пригласить друга",
        "settings": "⚙️ Настройки",
        "refresh": "🔄",
        "active_accounts": "АКТИВНЫЕ АККАУНТЫ",
        "no_accounts": "Нет активных аккаунтов — + добавить",
        "settings_title": "⚙️ Настройки",
        "api_key_label": "🔑 API ключ",
        "api_host_label": "🌐 API хост",
        "api_key_not_set": "❌ Не установлен",
        "api_key_set": "✅",
        "settings_note": "У каждого пользователя свой API ключ.",
        "language": "🌐 Язык",
        "select_language": "🌐 Выберите язык:",
        "language_changed": "✅ Язык изменён!",
        "subscription_title": "💳 Подписка",
        "no_active_sub": "❌ Нет активной подписки",
        "accounts_count": "📊 Аккаунтов: 0",
        "claims_count": "📊 Клеймов: 0",
        "available_plans": "✅ Доступные планы:",
        "monthly": "📆 Месячный – $15/мес",
        "monthly_desc": "├ 50 аккаунтов (любой сайт)\n└ Безлимитные клеймы",
        "claim_pack": "🎫 Пакет клеймов – $1/1200 клеймов",
        "claim_pack_desc": "├ Безлимит аккаунтов\n└ 1200 клеймов",
        "pay_with_crypto": "💎 Оплатить криптой",
        "select_crypto": "💎 Выберите криптовалюту\n\nПредпочитаемая монета:",
        "bnb": "🟡 BNB (BEP-20)",
        "sol": "🟠 SOL",
        "ltc": "⚪ LTC",
        "ton": "💎 TON",
        "trx": "🔴 TRX (TRC-20)",
        "doge": "🐕 DOGE",
        "wallet_address": "📍 Адрес кошелька:",
        "amounts": "💰 Введите любую сумму ($0.1 – $100 USD):",
        "send_exact": "⚠️ Отправьте точно введённую сумму",
        "submit_txid": "📝 После оплаты нажмите Отправить скриншот",
        "submit_txid_button": "📸 Отправить скриншот",
        "enter_amount": "💰 Введите сумму в USD (мин $0.1, макс $100):",
        "enter_txid": "📸 Теперь отправьте скриншот оплаты:",
        "deposit_request": "💸 Запрос пополнения от пользователя {user_id}\nСумма: ${amount}\nПодтверждение: {txid}",
        "approve": "✅ Подтвердить",
        "reject": "❌ Отклонить",
        "deposit_approved": "✅ Ваш депозит на сумму ${amount} подтверждён! Баланс обновлён.",
        "deposit_rejected": "❌ Ваш запрос отклонён. Попробуйте снова.",
        "txid_received": "📸 Скриншот получен! Администратор проверит и пополнит баланс.",
        "cancel": "❌ Отмена",
        "skip_cookies": "⏭️ Пропустить Cookies",
        "skip_ua": "⏭️ Пропустить UA",
        "add_account_title": "Добавить аккаунт — {crane}",
        "label": "🏷️ Метка: {label}",
        "send_email": "📧 Отправьте email аккаунта:",
        "cancel_abort": "/cancel для отмены.",
        "email_received": "📧 Email: <code>{email}</code>",
        "send_password": "🔑 Теперь отправьте пароль:",
        "password_ok": "🔑 Пароль: ✅",
        "cookies_optional": "🍪 Cookies (опционально — отправьте cookies или нажмите Skip):",
        "cookies_instruction": "F12 > Консоль > <code>document.cookie</code>",
        "cookies_skipped": "🍪 Cookies: ⏭️ Пропущено",
        "ua_optional": "🌐 User-Agent (опционально — отправьте UA или нажмите Skip):",
        "ua_instruction": "F12 > Консоль > <code>navigator.userAgent</code>",
        "cookies_received": "🍪 Cookies: ✅ ({len} симв.)",
        "account_added": "✅ <b>Аккаунт добавлен!</b>",
        "account_num": "{crane} #{num}",
        "cookies_status": "🍪 {status}",
        "ua_status": "🌐 UA: {status}",
        "main_menu": "🏠 Главное меню",
        "cancelled": "❌ Отменено.",
        "updated": "♻️ Обновлено!",
        "not_found": "Не найдено!",
        "api_key_prompt": "🔑 <b>XEvil API ключ</b>\n\nОтправьте ваш API ключ:\n\n/cancel для отмены.",
        "api_host_prompt": "🌐 <b>API хост</b>\n\nОтправьте API хост (например <code>sctg.xyz</code>):\n\n/cancel для отмены.",
        "referral_title": "🎁🎁 <b>Реферальная система</b>",
        "your_link": "🔗 <b>Ваша реферальная ссылка:</b>",
        "share_text": "📢 <b>Поделитесь ссылкой с друзьями!</b>\n├ Вы получаете: <b>+16 клеймов</b>\n└ Друг получает: <b>+8 клеймов</b>",
        "friends_joined": "👥 <b>Присоединилось друзей:</b> {count}",
        "bonus_earned": "📊 <b>Заработано бонусов:</b> {bonus}",
        "share_button": "📨 Поделиться с другом",
        "balance_title": "💰 <b>Мой баланс</b>",
        "current_balance": "💵 Текущий баланс: <b>${balance}</b>",
        "total_deposited": "📥 Всего пополнено: <b>${deposited}</b>",
        "total_spent": "📤 Потрачено на капчу: <b>${spent}</b>",
        "spent_note": "\n<i>Каждый клейм стоит $0.01 (1 цент)</i>",
        "add_balance_usage": "Admin: /add_balance <user_id> <amount>",
        "add_spent_usage": "Admin: /add_spent <user_id> <amount>",
        "balance_updated": "✅ Баланс пользователя {user_id} +${amount}, новый баланс: ${balance}",
        "spent_updated": "✅ Расход пользователя {user_id} +${amount}, новый расход: ${spent}",
        "invalid_amount": "❌ Неверная сумма. Введите число от 0.1 до 100.",
        "user_not_found": "❌ Пользователь не найден.",
        "admin_only": "❌ Только для администратора.",
        "referral_bonus": "🎉 Вы получили +16 клеймов! Вас пригласил {ref_id}",
        "referee_bonus": "🎉 Ваш друг получил +8 клеймов за переход по вашей ссылке!",
    }
}
